name: Build Project

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set UTF-8 encoding
        run: echo "JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install
